# https://jekyllrb.com/docs/collections/#manually-ordering-documents
collections:
  docs:
    order:
      - { heading: 'Prologue' }
      - index
      - cli
      - configuration
      - plugins
      - prerendering
      - web-workers
      - { heading: 'API' }
      - plugin-api
